# Created manually for ping-uin v0.1.7
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: altosaxplayer.ping-uin
PackageVersion: 0.1.7
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: ping-uin.exe
    PortableCommandAlias: ping-uin
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/altosaxplayer/ping-uin/releases/download/v0.1.7/ping-uin-windows-x86_64.zip
    InstallerSha256: C0446861D9E092272E7F1E939F82EE3C805EC7C5FDE2B31F8DDE4D770A0DD88D
ManifestType: installer
ManifestVersion: 1.6.0
